### ISSUE TITLE
Quiet audio

### ISSUE THREAD

**Issue by 3XAY** [Kolin63/BetsAndRegrets#23]
Make certain audio files louder (ask Colin which ones)

**Comment by Kolin63** [comment]
05.1 *shakey voice* N-no... I've really got to be more careful. I need to get back to my family (after he loses his third soul)

**Comment by Kolin63** [comment]
06.0 Devil: Grr... You've won.. I'm a man of my word, you are free... (when you win the game)

**Comment by Kolin63** [comment]
06.2 Narrator: After the man was let free, he lived life to the best of his ability. He became a loving husband and a caring father. He volunteered at his local soup kitchen, and was a good person overall. He had stopped lying and cheating his way through life. He was no longer, his own worst enemy. (After he wins)

**Comment by Kolin63** [comment]
08.0 I guess it's something (when he wins a day, has max souls, earnings are above 2x exclusive)

**Comment by Kolin63** [comment]
10.0 %*$@! (When he loses and no other conditions are met)

**Comment by Kolin63** [comment]
17.0 I'm so sorry for being a liar, this is why I'm here... (when he loses a day after he lost 3 souls)

**Comment by Kolin63** [comment]
20.0 *gasp* YES, YES! I HAVE A CHANCE (when he wins a day after losing 3 souls)

**Comment by Kolin63** [comment]
Oh! Oh yes! There is hope! (After he wins a day after losing 2 souls)

**Comment by 3XAY** [comment]
Just making sure you're using the files from the counterspellVoEdit folder right

**Comment by Kolin63** [comment]
Yes

**Comment by 3XAY** [comment]
Oh well that's for dramatic effect. Cuz when ayan originally edited the audio, he made sure to boost it so it's all audible, but not so they're all at the same volume.  (If they were, it would take some emotion out of it)

**Comment by Kolin63** [comment]
* Done at runtime rather than in the files
